name: routing

mgmt:
  network: clab_mgmt
  ipv4_subnet: 172.100.100.0/24
  ipv6_subnet: 2001:172:100:100::/80

topology:
  nodes:
    switch1:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.11
    
    switch2:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.12
    
    switch3:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.13
    
    switch4:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.14
    
    switch5:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.15
    
    switch6:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.16
    
    switch7:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.17
    
    switch8:
      kind: ceos
      image: ceoslab:4.27.2F
      mgmt_ipv4: 172.100.100.18
    
    host1:
      kind: linux
      image: nettest:1.0.0
      mgmt_ipv4: 172.100.100.51
    
    host2:
      kind: linux
      image: nettest:1.0.0
      mgmt_ipv4: 172.100.100.52

    host3:
      kind: linux
      image: nettest:1.0.0
      mgmt_ipv4: 172.100.100.53

  links:
    - endpoints: ["switch1:eth1", "switch2:eth1"]
    - endpoints: ["switch1:eth2", "switch3:eth2"]
    - endpoints: ["switch1:eth3", "switch4:eth4"]
    - endpoints: ["switch2:eth3", "switch5:eth1"]
    - endpoints: ["switch2:eth4", "switch3:eth3"]
    - endpoints: ["switch3:eth1", "switch4:eth1"]
    - endpoints: ["switch4:eth2", "switch2:eth2"]
    - endpoints: ["switch4:eth3", "switch5:eth2"]
    - endpoints: ["switch5:eth3", "switch6:eth1"]
    - endpoints: ["switch5:eth4", "switch7:eth1"]
    - endpoints: ["switch6:eth2", "switch8:eth1"]
    - endpoints: ["switch6:eth3", "switch7:eth3"]
    - endpoints: ["switch7:eth2", "switch8:eth2"]
    - endpoints: ["host1:eth1", "switch1:eth5"]
    - endpoints: ["host2:eth1", "switch3:eth5"]
    - endpoints: ["host3:eth1", "switch8:eth5"]
